version: "3.9"

x-biggie-common:
  &biggie-common
  environment:
    &biggie-common-env
    MONGODB_URI: "${MONGODB_URI}"
    DB_NAME: "${DB_NAME}"
  volumes:
    - "${VOLUME_MOUNT}"

services:

  nginx:
    image: nginx
    container_name: biggie_nginx
    volumes:
      - ./conf/nginx/docker_base.conf:/etc/nginx/nginx.conf:ro
      - ./conf/nginx/certificate.conf:/etc/nginx/certificate.conf:ro
      - ./logs/nginx:/var/log/nginx
      - ./conf/nginx/app_docker.conf:/etc/nginx/sites-enabled/app_docker.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro  # certificate of the host machine
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - api_prod
    profiles:
      - live_prod

  api_test:
    container_name: biggie_api_test
    image: "ghcr.io/pierrz/biggie_api_img:latest"
    environment:
      <<: *biggie-common-env
    command: pytest -v
    depends_on:
      - mongo
    profiles:
      - test

  api_prod:
    <<: *biggie-common
    container_name: biggie_api_prod
    image: "ghcr.io/pierrz/biggie_api_img:latest"
    command: uvicorn main:app --host 0.0.0.0 --reload --log-level error
    depends_on:
      - mongo
    ports:
      - "8000:8000"

  harvester_test:
    container_name: biggie_harvester_test
    image: "ghcr.io/pierrz/biggie_harvester_img:latest"
    environment:
      API_PUBLIC_KEY: "${API_PUBLIC_KEY}"
      API_PRIVATE_KEY: "${API_PRIVATE_KEY}"
    volumes:
      - "${VOLUME_MOUNT}"
    command: pytest -v --asyncio-mode=strict
    profiles:
      - test

  harvester_prod:
    container_name: biggie_harvester_prod
    image: "ghcr.io/pierrz/biggie_harvester_img:latest"
    environment:
      API_PUBLIC_KEY: "${API_PUBLIC_KEY}"
      API_PRIVATE_KEY: "${API_PRIVATE_KEY}"
    volumes:
      - "${VOLUME_MOUNT}"
    command: python3 -m __init__

  pyspark_test:
    container_name: biggie_pyspark_test
    image: "ghcr.io/pierrz/biggie_pyspark_img:latest"
    environment:
      <<: *biggie-common-env
    depends_on:
      - mongo
    command: python3.9 -m pytest -v
    profiles:
      - test

  pyspark_prod:
    <<: *biggie-common
    container_name: biggie_pyspark_prod
    image: "ghcr.io/pierrz/biggie_pyspark_img:latest"
    depends_on:
      - harvester_prod
      - mongo
    command: python3.9 -m __init__
