version: "3.9"

volumes:
  biggie_db:
    name: biggie_db

services:

  nginx:
    image: nginx
    container_name: biggie_nginx
    volumes:
      - ./setup/nginx/docker_base.conf:/etc/nginx/nginx.conf:ro
      - ./setup/nginx/certificate.conf:/etc/nginx/certificate.conf:ro
      - ./logs/nginx:/var/log/nginx
      - /etc/letsencrypt:/etc/letsencrypt:ro
    ports:
      - "80:80"
      - "443:443"
    profiles:
      - live_prod

  rabbitmq:
    container_name: biggie_rabbitmq
    image: rabbitmq:3.8-management
    restart: on-failure
    ports:
      - "5672:5672"
      - "15672:15672"

  mongo:
    image: mongo:latest
    container_name: biggie_mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_INITDB_ROOT_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_INITDB_ROOT_PASSWORD}"
    # TODO: implement authentication for api container calls
  #    command:
#      - mongo --config /etc/mongo/mongod.conf
#    volumes:
#      - ./setup/mongo/mongod.conf:/etc/mongo/mongod.conf:ro
