# TODO:
#  - mount/retrieve Spark, Mongo and Postgres logs
#  - implement Mongo conf for authentication
#  - debug setup

x-biggie-common:
  environment:
    &biggie-common-env
    MONGODB_URI: "${MONGODB_URI}"
    DB_NAME: "${DB_NAME}"
    DB_USER: "${DB_USER}"
    DB_PASSWORD: "${DB_PASSWORD}"

x-biggie-orchestrator:
  &biggie-orchestrator
  environment:
    &biggie-orchestrator-env
    <<: *biggie-common-env
    TOKEN_GITHUB_API: "${TOKEN_GITHUB_API}"
    CELERY_BROKER_URL: "${CELERY_BROKER_URL}"
    CELERY_RESULT_BACKEND: "${CELERY_RESULT_BACKEND}"
    # PYTHON_ENABLE_DEBUGGER: 1   # debug mode
  volumes:
    - ${LOGS_DIR}/orchestrator:/opt/orchestrator/logs
    - ${DATA_DIR}:/opt/data

volumes:
  biggie_vmongo:
    name: biggie_vmongo
  biggie_vpostgres:
    name: biggie_vpostgres
  biggie_vrabbitmq:
    name: biggie_vrabbitmq

networks:
  biggie-network:
    name: biggie_network
    driver: bridge
    ipam:
      config:
        # range starts at 172.22 to avoid conflicts with the bridge network (172.17)
        - subnet: 172.22.0.0/16

services:

  # nginx:
  #   build: nginx
  #   container_name: biggie_nginx
  #   volumes:
  #     - ./conf/nginx/docker_base.conf:/etc/nginx/nginx.conf:ro
  #     - ./conf/nginx/certificate.conf:/etc/nginx/certificate.conf:ro
  #     - ./logs/nginx:/var/log/nginx
  #     - ./conf/nginx/app_docker.conf:/etc/nginx/sites-enabled/app_docker.conf:ro
  #     - /etc/letsencrypt:/etc/letsencrypt:ro  # certificate of the host machine
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   depends_on:
  #     - api_prod
  #   profiles:
  #     - live_prod

  mongo:
    container_name: biggie_mongo
    build: db/mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_INITDB_ROOT_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_INITDB_ROOT_PASSWORD}"
    volumes:
      - biggie_vmongo:/data/db
      - ${LOGS_DIR}/mongodb:/var/log/mongodb
      # TODO: implement authentication for api container calls
      # - ./db/mongo/mongod.conf:/etc/mongo/mongod.conf:ro
    networks:
      biggie-network:
        ipv4_address: 172.22.0.101

  postgres:
    container_name: biggie_postgres
    build: db/postgres
    restart: always
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      DB_NAME: "${DB_NAME}"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - biggie_vpostgres:/var/lib/postgresql/data
      - ./db/postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ${LOGS_DIR}/postgresql:/var/log/postgresql #/postgresql-14.9-main.log
    ports:
      - "5432:5432"
    networks:
      biggie-network:
        ipv4_address: 172.22.0.102

  api-test:
    container_name: biggie_api-test
    build:
      context: .
      dockerfile: api/Dockerfile
      args:
        - TEST_MODE="True"
    environment:
      <<: *biggie-common-env
    command: pytest -vv
    depends_on:
      - mongo
      - postgres
    profiles:
      - test
    volumes:
      - ${LOGS_DIR}/api:/var/log/api/
      # Dev speed up (no build)
      # - ./api:/opt/api
      # - ./db/mongo_db.py:/opt/api/src/db/mongo_db.py
      # - ./db/postgres_db.py:/opt/api/src/db/postgres_db.py
      # - ./commons:/opt/api/src/commons
    networks:
      biggie-network:
        ipv4_address: 172.22.0.121

  api-prod:
    container_name: biggie_api-prod
    build:
      context: .
      dockerfile: api/Dockerfile
    environment:
      <<: *biggie-common-env
    command: uvicorn main:app --host 0.0.0.0 --reload --log-level debug
    depends_on:
      - mongo
      - postgres
    ports:
      - "8100:8100"
    profiles:
      - prod_full
      - prod_analytics
    volumes:
      - ${LOGS_DIR}/api:/var/log/api/
      - ${DATA_DIR}/github_events/diagrams:/opt/api/templates/github_events/diagrams
      # Dev speed up (no build)
      # - ./api:/opt/api
      # - ./db/mongo_db.py:/opt/api/src/db/mongo_db.py
      # - ./db/postgres_db.py:/opt/api/src/db/postgres_db.py
      # - ./commons:/opt/api/src/commons
    networks:
      biggie-network:
        ipv4_address: 172.22.0.122

  orchestrator-test:
    container_name: biggie_orchestrator-test
    build:
      context: .
      dockerfile: orchestrator/Dockerfile
      args:
        - TEST_MODE="True"
    <<: *biggie-orchestrator
    depends_on:
      - rabbitmq
      - mongo
      - postgres
      - spark-master
      - spark-worker-1
      - spark-worker-2
    command: python3 -m pytest -vv
    profiles:
      - test
    restart: on-failure
    networks:
      biggie-network:
        ipv4_address: 172.22.0.131

  orchestrator-prod:
    container_name: biggie_orchestrator-prod
    build:
      context: .
      dockerfile: orchestrator/Dockerfile
    <<: *biggie-orchestrator
    depends_on:
      - rabbitmq
      - mongo
      - postgres
      - spark-master
      - spark-worker-1
      - spark-worker-2
    command: sh run.sh
    profiles:
      - prod_full
      - prod_acquisition
    restart: on-failure
    # ports:
    #   - "5678:5678"  # Expose debugging port
    networks:
      biggie-network:
        ipv4_address: 172.22.0.132

  rabbitmq:
    container_name: biggie_rabbitmq
    image: rabbitmq:3.13.7-management
    restart: on-failure
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - biggie_vrabbitmq:/var/lib/rabbitmq
      - ${LOGS_DIR}/rabbitmq:/var/log/rabbitmq
    profiles:
      - test
      - prod_full
      - prod_acquisition
    networks:
      biggie-network:
        ipv4_address: 172.22.0.133

  spark-master:
    container_name: biggie_spark-master
    build: spark_cluster
    environment:
      - SPARK_MODE=master
    ports:
      - "7077:7077"  # Spark master port
      - "8080:8080"  # Web UI for Spark master
    depends_on:
      - mongo
      - postgres
    volumes:
      - ${LOGS_DIR}/spark:/opt/bitnami/spark/logs
    profiles:
      - test
      - prod_full
      - prod_acquisition
    networks:
      biggie-network:
        ipv4_address: 172.22.0.141

  spark-worker-1:
    container_name: biggie_spark-worker-1
    build: spark_cluster
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    depends_on:
      - spark-master
      - mongo
      - postgres
    ports:
      - "8091:8091"  # Web UI for this worker
    volumes:
      - ${LOGS_DIR}/spark:/opt/bitnami/spark/logs
    profiles:
      - test
      - prod_full
      - prod_acquisition
    networks:
      biggie-network:
        ipv4_address: 172.22.0.142

  spark-worker-2:
    container_name: biggie_spark-worker-2
    build: spark_cluster
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    depends_on:
      - spark-master
      - mongo
      - postgres
    ports:
      - "8092:8092"  # Web UI for this worker
    volumes:
      - ${LOGS_DIR}/spark:/opt/bitnami/spark/logs
    profiles:
      - test
      - prod_full
      - prod_acquisition
    networks:
      biggie-network:
        ipv4_address: 172.22.0.143
