name: "${COMPOSE_PREFIX}biggie"

services:

  flower:
    container_name: ${COMPOSE_PREFIX}biggie_flower
    image: mher/flower:2.0.1
    command: celery --broker=${CELERY_BROKER_URL} flower
    environment:
      CELERY_BROKER_URL: "${CELERY_BROKER_URL}"
      CELERY_RESULT_BACKEND: "${CELERY_RESULT_BACKEND}"
    ports:
      - "${FLOWER_PORT}:5555"
    depends_on:
      - orchestrator-prod
    profiles:
      - prod_full
      - prod_acquisition
    networks:
      biggie-network:
        ipv4_address: ${DOCKER_SUBNET_BASE}.151

  mongo-express:
    image: mongo-express:1.0.2-20
    container_name: ${COMPOSE_PREFIX}biggie_mongoex
    restart: always
    ports:
      - "${ME_CONFIG_PORT}:8081"
    environment:
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_MONGODB_ADMINUSERNAME: "${ME_CONFIG_MONGODB_ADMINUSERNAME}"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "${ME_CONFIG_MONGODB_ADMINPASSWORD}"
      ME_CONFIG_BASICAUTH_USERNAME: "${ME_CONFIG_BASICAUTH_USERNAME}"
      ME_CONFIG_BASICAUTH_PASSWORD: "${ME_CONFIG_BASICAUTH_PASSWORD}"
      ME_CONFIG_MONGODB_URL: "mongodb://${ME_CONFIG_MONGODB_ADMINUSERNAME}:${ME_CONFIG_MONGODB_ADMINPASSWORD}@${COMPOSE_PREFIX}biggie_mongo:27017/?authSource=admin"
    depends_on:
      - mongo
    profiles:
      - prod_full
      - prod_analytics
      - prod_acquisition
    networks:
      biggie-network:
        ipv4_address: ${DOCKER_SUBNET_BASE}.152

  dbeaver:
    container_name: ${COMPOSE_PREFIX}biggie_dbeaver
    image: dbeaver/cloudbeaver:24.2.2
    restart: always
    volumes:
      - ${DATA_DIR}/cloudbeaver/workspace:/opt/cloudbeaver/workspace
    depends_on:
      - postgres
    profiles:
      - prod_full
      - prod_analytics
      - prod_acquisition
    ports:
      - "8180:8978"
    networks:
      biggie-network:
        ipv4_address: ${DOCKER_SUBNET_BASE}.153

  # pgadmin:
  #   container_name: ${COMPOSE_PREFIX}biggie_pgadmin
  #   # image: dpage/pgadmin4:8.11.0
  #   build:
  #     context: .
  #     dockerfile: db/postgres/Dockerfile.pgadmin
  #     args:
  #       - POSTGRES_PORT=${POSTGRES_PORT}
  #       - POSTGRES_USER=${POSTGRES_USER}
  #       - POSTGRES_HOST=${COMPOSE_PREFIX}biggie_postgres
  #       - MAINTENANCE_DB=${POSTGRES_DB}
  #   restart: always
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: "${PGADMIN_DEFAULT_EMAIL}"
  #     PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_DEFAULT_PASSWORD}"
  #     PGADMIN_ENABLE_X_FORWARD_HEADERS: True
  #   volumes:
  #     - ./db/postgres/pgadmin_conf/config_local.py:/pgadmin4/config_local.py
  #   depends_on:
  #     - postgres
  #   profiles:
  #     - prod_full
  #     - prod_analytics
  #     - prod_acquisition
  #   ports:
  #     - "${PGADMIN_DEFAULT_PORT}:80"
  #   networks:
  #     biggie-network:
  #       ipv4_address: ${DOCKER_SUBNET_BASE}.153
