version: "3.9"

services:

  nginx:
    volumes:
      - ./setup/nginx/monitor_docker.conf:/etc/nginx/sites-enabled/monitor_docker.conf:ro
    depends_on:
      - flower
    profiles:
      - live_prod

  flower:
    container_name: biggie_flower
    image: mher/flower:latest
    command: ["celery", "--broker=${CELERY_BROKER_URL}", "flower"]
    environment:
      CELERY_BROKER_URL: "${CELERY_BROKER_URL}"
      CELERY_RESULT_BACKEND: "${CELERY_RESULT_BACKEND}"
    ports:
      - "49555:5555"
    depends_on:
      - celery

  mongo-express:
    image: mongo-express:latest
    container_name: biggie_mongoex
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_MONGODB_ADMINUSERNAME: "${ME_CONFIG_MONGODB_ADMINUSERNAME}"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "${ME_CONFIG_MONGODB_ADMINPASSWORD}"
      ME_CONFIG_BASICAUTH_USERNAME: "${ME_CONFIG_BASICAUTH_USERNAME}"
      ME_CONFIG_BASICAUTH_PASSWORD: "${ME_CONFIG_BASICAUTH_PASSWORD}"
      ME_CONFIG_MONGODB_URL: "${MONGODB_URI}"
    depends_on:
      - mongo
