version: "3.9"

x-biggie-common:
  environment:
    &biggie-common-env
    MONGODB_URI: "${MONGODB_URI}"
    DB_NAME: "${DB_NAME}"

services:

  nginx:
    volumes:
      - ./conf/nginx/app_docker.conf:/etc/nginx/sites-enabled/app_docker.conf:ro
    depends_on:
      - api_prod
    profiles:
      - live_prod

  api_test:
    container_name: biggie_api_test
    image: biggie_api_img
    build:
      context: .
      dockerfile: api/Dockerfile-api
    environment:
      <<: *biggie-common-env
    volumes:
      - ./data:/opt/data
    command: pytest -v
    depends_on:
      - mongo
    profiles:
      - test

  api_prod:
    container_name: biggie_api_prod
    image: biggie_api_img
    environment:
      <<: *biggie-common-env
    command: uvicorn main:app --host 0.0.0.0 --reload --log-level error
    depends_on:
      - mongo
    volumes:
      - ./data:/opt/data
    ports:
      - "${APP_PORT}"

  harvester:
    container_name: biggie_harvester
    build:
      context: .
      dockerfile: harvester/Dockerfile-harvester
    environment:
      API_PUBLIC_KEY: "${API_PUBLIC_KEY}"
      API_PRIVATE_KEY: "${API_PRIVATE_KEY}"
    volumes:
      - ./data:/opt/data
    profiles:
      - import_data

  spark_test:
    container_name: biggie_spark_test
    image: biggie_spark_img
    build:
      context: .
      dockerfile: spark/Dockerfile-spark
    environment:
      <<: *biggie-common-env
    depends_on:
      - mongo
    command: python3.9 -m pytest -v
    profiles:
      - import_data
      - test

  spark_prod:
    container_name: biggie_spark_prod
    image: biggie_spark_img
    environment:
      <<: *biggie-common-env
    volumes:
      - ./data:/opt/data
    depends_on:
      - harvester
    command: python3.9 -m __init__
    profiles:
      - import_data
