version: "3.9"

x-biggie-common:
  environment:
    &biggie-common-env
    CELERY_BROKER_URL: "${CELERY_BROKER_URL}"
    CELERY_RESULT_BACKEND: "${CELERY_RESULT_BACKEND}"
    DB_NAME: "${DB_NAME}"
    API_PUBLIC_KEY: "${API_PUBLIC_KEY}"
    API_PRIVATE_KEY: "${API_PRIVATE_KEY}"
    MONGODB_URI: "${MONGODB_URI}"

services:

  nginx:
    volumes:
      - ./conf/nginx/app_docker.conf:/etc/nginx/sites-enabled/app_docker.conf:ro
    depends_on:
      - api_prod
    profiles:
      - live_prod

  api_test:
    container_name: biggie_api_test
    image: biggie_img
    environment:
      <<: *biggie-common-env
      APP_MODE: "TEST"
    volumes:
      - ./data:/opt/data
    command: pytest -v
    depends_on:
      - celery
      - mongo

  api_prod:
    container_name: biggie_api_prod
    image: biggie_img
    environment:
      <<: *biggie-common-env
      APP_MODE: "PROD"
    command: uvicorn main:app --host 0.0.0.0 --reload --log-level error
    depends_on:
      #      - mongo
      - api_test
    volumes:
      - ./data:/opt/data
    ports:
      - "${APP_PORT}"

  celery:
    container_name: biggie_celery
    image: biggie_img
    build:
      context: .
      dockerfile: app/Dockerfile
    volumes:
      - ./logs/celery:/opt/logs
      - ./data:/opt/data
    environment:
      # TODO: exclude app related variables
      <<: *biggie-common-env
    depends_on:
      - rabbitmq
    command: celery --app=worker.celery worker --loglevel=info --logfile=../logs/celery.log
