version: "3.9"

x-ukr-dp-common:
  environment:
    &ukr-dp-common-env
    MONGODB_URI: "${MONGODB_URI}"
    DB_NAME: "${DB_NAME}"
    DB_USER: "${DB_USER}"
    DB_PASSWORD: "${DB_PASSWORD}"

x-ukr-dp-celery-prod:
  &ukr-dp-celery-prod
  environment:
    &ukr-dp-celery-prod-env
    <<: *ukr-dp-common-env
    TOKEN_GITHUB_API: "${TOKEN_GITHUB_API}"
    CELERY_BROKER_URL: "${CELERY_BROKER_URL}"
    CELERY_RESULT_BACKEND: "${CELERY_RESULT_BACKEND}"
  volumes:
    - ./logs/celery_app:/opt/celery_app/logs
    - "${VOLUME_MOUNT}"
    - ./data/events/diagrams:/opt/data/diagrams  # necessary for the cleaning task

x-ukr-dp-celery-test:
  &ukr-dp-celery-test
  environment:
    <<: *ukr-dp-celery-prod-env
    TEST: "True"
  volumes:
    - ./logs/celery_app:/opt/celery_app/logs
    - "${VOLUME_MOUNT}"

volumes:
  ukr-dp_vmongo:
    name: ukr-dp_vmongo
  ukr-dp_vpostgres:
    name: ukr-dp_vpostgres
  ukr-dp_vrabbitmq:
    name: ukr-dp_vrabbitmq

services:

  nginx:
    image: nginx
    container_name: ukr-dp_nginx
    volumes:
      - ./conf/nginx/docker_base.conf:/etc/nginx/nginx.conf:ro
      - ./conf/nginx/certificate.conf:/etc/nginx/certificate.conf:ro
      - ./logs/nginx:/var/log/nginx
      - ./conf/nginx/app_docker.conf:/etc/nginx/sites-enabled/app_docker.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro  # certificate of the host machine
    ports:
      - "80:80"
      - "443:443"
    depends_on:
#      - pgadmin
      - api_prod
    profiles:
      - live_prod

  mongo:
    image: mongo:5.0.8
    container_name: ukr-dp_mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_INITDB_ROOT_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_INITDB_ROOT_PASSWORD}"
    volumes:
      - ukr-dp_vmongo:/data/db
      # TODO: implement authentication for api container calls
      # - ./setup/mongo/mongod.conf:/etc/mongo/mongod.conf:ro

  postgres:
    container_name: ukr-dp_postgres
    build:
      context: .
      dockerfile: conf/postgres/Dockerfile
    restart: always
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      DB_NAME: "${DB_NAME}"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
    image: postgres:latest
    volumes:
      - ukr-dp_vpostgres:/var/lib/postgresql/data
      # todo: implement that to remove the dockerfile
      # - ./conf/postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  api_test:
    container_name: ukr-dp_api_test
    image: ukr-dp_api_img
    build:
      context: .
      dockerfile: api/Dockerfile
    environment:
      <<: *ukr-dp-common-env
      TEST: "True"
    command: pytest -v
    depends_on:
      - mongo
      - postgres
    profiles:
      - test

  api_prod:
    container_name: ukr-dp_api_prod
    image: ukr-dp_api_img
    environment:
      <<: *ukr-dp-common-env
    command: uvicorn main:app --host 0.0.0.0 --reload --log-level error
    depends_on:
      - mongo
      - postgres
    ports:
      - "8000:8000"
    profiles:
      - prod
    volumes:
      - ./data/events/diagrams:/opt/api/templates/diagrams

  celery_test:
    container_name: ukr-dp_celery_test
    build:
      context: .
      dockerfile: celery_app/Dockerfile
    image: ukr-dp_celery_img
    <<: *ukr-dp-celery-test
    depends_on:
      - rabbitmq
      - mongo
      - postgres
    command: python3.10 -m pytest -vv
    profiles:
      - test
    restart: on-failure

  celery_prod:
    container_name: ukr-dp_celery_prod
    image: ukr-dp_celery_img
    <<: *ukr-dp-celery-prod
    depends_on:
      - rabbitmq
      - mongo
      - postgres
    command: sh run.sh
    profiles:
      - prod
      - monitoring
    restart: on-failure

  rabbitmq:
    container_name: ukr-dp_rabbitmq
    image: rabbitmq:3.8-management
    restart: on-failure
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ukr-dp_vrabbitmq:/var/lib/rabbitmq
      - ./logs/rabbitmq:/var/log/rabbitmq
