[tool.poetry]
name = "biggie"
version = "0.4.3"
description = "dev setup"
authors = ["Pierre-Edouard Barrault"]

[tool.poetry.dependencies]
python = ">=3.10,<3.11"

[tool.poetry.dev-dependencies]
black = "==22.6.0"
flake8 = "==5.0.4"
isort = "==5.10.1"
pre-commit = "==2.20.0"
pylint = "==2.14.5"

[build-system]
requires = ["poetry_core>=1.1.14"]  # not working with 1.1.7 and python3.10.4
build-backend = "poetry.masonry.api"

[tool.isort]
profile = "black"

[tool.black]
line-length = 88
target-version = ['py38']
include = '\.pyi?$'
extend-exclude = '''
/(
  # directories
  | \.git
  | \.mypy_cache
  | \.venv
  | \__pycache__
)/
'''
