[tool.poetry]
name = "biggie"
version = "0.4.3"
description = "Biggie. Celery containers (test & prod)"
authors = ["Pierre-Edouard Barrault"]

[tool.poetry.dependencies]
python = ">=3.10,<3.11"
aiohttp = "==3.8.1"
asyncio = "==3.4.3"
celery = "==5.2.7"
importlib_metadata = "==3.10"       # TODO: check if necessary
pandas = "==1.4.3"
psycopg2-binary = "==2.9.3"
pydantic = "==1.9.1"
pymongo = "==4.2.0"                 # TODO: check if necessary
pyspark = "==3.5.2"
pytest = "==7.1.2"
pytest-asyncio = "==0.19.0"
requests = "==2.28.1"
SQLAlchemy = "==1.4.39"
typing = "==3.7.4.3"
# warnings for these 2 (blockers on fix/update end 2022)
chardet = "==5.0.0"
urllib3 = "==1.26.12"

[build-system]
requires = ["poetry-core>=1.1"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
pythonpath = [ "/opt/celery_app", ]
asyncio_mode = "strict"
filterwarnings = [
    "error",
    "ignore::pytest.PytestCollectionWarning",
    "ignore::pytest.PytestUnraisableExceptionWarning",
    # see references
    # https://github.com/celery/kombu/issues/1339
    # https://github.com/celery/celery/issues/7528
    "ignore::DeprecationWarning"    # to avoid DeprecationWarning due to Celery
]
