name: Docker build-push template
description: This is a custom action to build and push a docker image
author: pierrz

inputs:
  name:
    required: true
  src:
    required: true
  registry:
    required: true
  actor:
    required: true
  token:
    required: true
  image:
    required: true
  tag:
    required: true
  labels:
    required: true

runs:
  using: "composite"
  steps:

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3.6.1

    # Log in to the Container registry
    - name: Log in to the Container registry
      uses: docker/login-action@v3.3.0
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.actor }}
        password: ${{ inputs.token }}

    # Extract metadata (tags, labels) for Docker
    - name: Extract metadata (tags, labels) for Docker - ${{ inputs.name }}
      id: meta
      uses: docker/metadata-action@v5.5.1
      with:
        images: ${{ inputs.registry }}/${{ inputs.image }}

    # Build and push Docker image
    - name: Build and push Docker image - ${{ inputs.name }}
      uses: docker/build-push-action@v6.7.0
      with:
        context: .
        file: ${{ inputs.src }}/Dockerfile
        push: true
        tags: ${{ inputs.registry }}/${{ inputs.image }}:latest, ${{ inputs.registry }}/${{ inputs.image }}:${{ inputs.tag }}
        labels: ${{ inputs.tag }}, ${{ inputs.labels }}
