FROM dpage/pgadmin4:8.11.0

ARG POSTGRES_PORT \
    POSTGRES_USER \
    POSTGRES_HOST \
    MAINTENANCE_DB

USER pgadmin
RUN echo '{\
 "Servers":\
 {\
  "1":\
  {\
   "Name": "Biggie",\
   "Group": "Docker",\
   "Port": 5432,\
   "Username": "'$POSTGRES_USER'",\
   "Host": "'$POSTGRES_HOST'",\
   "SSLMode": "prefer",\
   "MaintenanceDB": "'$MAINTENANCE_DB'"\
  }\
 }\
}' | python3 -m json.tool > /pgadmin4/servers.json

# RUN chown pgadmin:pgadmin /pgadmin4/servers.json
