FROM rabbitmq:3.13.7-management

# ARG RABBITMQ_PORT

# RUN echo "listeners.tcp.default = ${RABBITMQ_PORT}" >> /etc/rabbitmq/rabbitmq.conf \
#     echo "management.tcp.port = 1${RABBITMQ_PORT}" >> /etc/rabbitmq/rabbitmq.conf
