[tool.poetry]
name = "biggie"
version = "0.3.0"
description = "FastAPI containers (prod and test)"
authors = ["Pierre-Edouard Barrault"]

[tool.poetry.dependencies]
python = ">=3.9,<3.10"   # pinned after fastapi docker image
fastapi = "==0.75.2"
Jinja2 = "==3.1.2"
pandas = "==1.4.2"
pydantic = "==1.9.0"
pymongo = "==4.1.1"
pytest = "==7.1.2"
typing = "==3.7.4.3"
uvicorn = "==0.17.6"

[tool.poetry.dev-dependencies]
black = "==22.3.0"
flake8 = "==4.0.1"
isort = "==5.10.1"
pre-commit = "==2.19.0"
pylint = "==2.13.8"

[build-system]
requires = ["poetry_core>=1.0.0"]
build-backend = "poetry.masonry.api"

[tool.pytest.ini_options]
filterwarnings = [
    "error"
]
