[tool.poetry]
name = "biggie"
version = "0.4.5"
description = "Biggie. FastAPI containers (test & prod)"
authors = ["Pierre-Edouard Barrault"]

[tool.poetry.dependencies]
python = ">=3.11,<3.12"
fastapi = "==0.79.0"
Jinja2 = "==3.1.2"
pandas = "==1.4.3"
plotly = "==5.9.0"
psycopg2-binary = "==2.9.3"
pydantic = "==1.9.1"
pymongo = "==4.8.0"
pytest = "==7.1.2"
SQLAlchemy = "==1.4.39"
typing = "==3.7.4.3"
uvicorn = "==0.18.2"

[build-system]
requires = ["poetry_core>=1.8.3"]
build-backend = "poetry.masonry.api"

[tool.pytest.ini_options]
pythonpath = [ "/opt/api", ]
filterwarnings = [
    "error"
]
