name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy to Server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
        # run: |
        #   echo "$SSH_PRIVATE_KEY" > private_key
        #   chmod 600 private_key
        #   scp -i private_key docker-compose.yml $SERVER_USER@$SERVER_HOST:/path/to/deployment/
        #   ssh -i private_key $SERVER_USER@$SERVER_HOST << 'EOF'
        #     cd /path/to/deployment/
        #     docker-compose pull
        #     docker-compose up -d
        #   EOF
        #   rm private_key
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key
          chmod 600 private_key
          tar czf repo.tar.gz .
          scp -i private_key repo.tar.gz $SERVER_USER@$SERVER_HOST:/path/to/deployment/
          ssh -i private_key $SERVER_USER@$SERVER_HOST << 'EOF'
            cd /path/to/deployment/
            tar xzf repo.tar.gz
            docker-compose pull
            docker-compose up -d
          EOF
          rm private_key
