name: CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed
  workflow_dispatch:      # manual trigger

jobs:

  deploy:
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}

    permissions:
      # The "id-token: write" permission is required or Machine ID will not be
      # able to authenticate with the cluster.
      id-token: write
      contents: read
    # false
    # if: true
    runs-on: ubuntu-latest

    # env:
    #   SCW_ACCESS_KEY: ${{ secrets.SCALEWAY_ACCESS_KEY }}
    #   SCW_SECRET_KEY: ${{ secrets.SCALEWAY_SECRET_KEY }}
    #   SCW_DEFAULT_PROJECT_ID: ${{ secrets.SCALEWAY_PROJECT_ID }}

    env:
        SCW_ACCESS_KEY: ${{ secrets.SCALEWAY_ACCESS_KEY }}
        SCW_SECRET_KEY: ${{ secrets.SCALEWAY_SECRET_KEY }}
        SCW_DEFAULT_PROJECT_ID: ${{ secrets.SCALEWAY_PROJECT_ID }}
        TF_VAR_scaleway_access_key: ${{ secrets.SCALEWAY_ACCESS_KEY }}
        TF_VAR_scaleway_secret_key: ${{ secrets.SCALEWAY_SECRET_KEY }}
        TF_VAR_scaleway_organization_id: ${{ secrets.SCALEWAY_ORGANIZATION_ID }}
        TF_VAR_scaleway_project_id: ${{ secrets.SCALEWAY_PROJECT_ID }}
        TF_VAR_scaleway_server_name: ${{ secrets.SCALEWAY_SERVER_NAME }}
        TF_VAR_scaleway_server_id: ${{ secrets.SCALEWAY_SERVER_ID }}
        TF_VAR_scaleway_server_os_id: ${{ secrets.SCALEWAY_SERVER_OS_ID }}
        TF_VAR_scaleway_server_public_ip: ${{ secrets.SCALEWAY_SERVER_PUBLIC_IP }}
        TF_VAR_scaleway_server_user: ${{ secrets.SCALEWAY_SERVER_USER }}
        TF_VAR_scaleway_ssh_key_names: ${{ secrets.SCALEWAY_SSH_KEY_NAMES }}
        # TF_VAR_scaleway_server_password: ${{ secrets.SCALEWAY_SERVER_PASSWORD }}
        # TF_VAR_scaleway_ssh_key_id: ${{ secrets.SCALEWAY_SSH_KEY_ID }}
        TF_VAR_scaleway_zone: ${{ secrets.SCALEWAY_ZONE }}
        TF_LOG: DEBUG

    steps:

    - name: Checkout repository
      uses: actions/checkout@v4.1.7

    - name: Fetch Teleport binaries
      uses: teleport-actions/setup@v1.0.6
      with:
        version: 16.4.2

    # server access example
    - name: Fetch credentials using Machine ID
      id: auth
      uses: teleport-actions/auth@v2
      with:
        proxy: ${{ secrets.TELEPORT_PROXY }}
        token: ${{ secrets.TELEPORT_BOT }}
        # Enable the submission of anonymous usage telemetry. This
        # helps us shape the future development of `tbot`. You can disable this
        # by omitting this.
        anonymous-telemetry: 1

    - name: Check Teleport connection
      run: |
        tsh status
        tsh ls

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3.1.2

    - name: Create SSH private key file
      run: echo "${{ secrets.SCALEWAY_SSH_PRIVATE_KEY }}" > /tmp/id_key

    - name: Initialize Terraform
      uses: ./.github/actions/terraform
      with:
        command: init
      # run: terraform init
      # working-directory: ./terraform

    - name: Terraform Format
      uses: ./.github/actions/terraform
      with:
        command: fmt -check
      # run: terraform fmt -check
      # working-directory: ./terraform

    - name: Terraform Plan
      uses: ./.github/actions/terraform
      with:
        command: plan
      # env:
      #   SCW_ACCESS_KEY: ${{ secrets.SCALEWAY_ACCESS_KEY }}
      #   SCW_SECRET_KEY: ${{ secrets.SCALEWAY_SECRET_KEY }}
      #   SCW_DEFAULT_PROJECT_ID: ${{ secrets.SCALEWAY_PROJECT_ID }}
      #   TF_VAR_scaleway_access_key: ${{ secrets.SCALEWAY_ACCESS_KEY }}
      #   TF_VAR_scaleway_secret_key: ${{ secrets.SCALEWAY_SECRET_KEY }}
      #   TF_VAR_scaleway_organization_id: ${{ secrets.SCALEWAY_ORGANIZATION_ID }}
      #   TF_VAR_scaleway_project_id: ${{ secrets.SCALEWAY_PROJECT_ID }}
      #   TF_VAR_scaleway_server_name: ${{ secrets.SCALEWAY_SERVER_NAME }}
      #   TF_VAR_scaleway_server_id: ${{ secrets.SCALEWAY_SERVER_ID }}
      #   TF_VAR_scaleway_server_os_id: ${{ secrets.SCALEWAY_SERVER_OS_ID }}
      #   TF_VAR_scaleway_server_public_ip: ${{ secrets.SCALEWAY_SERVER_PUBLIC_IP }}
      #   TF_VAR_scaleway_server_user: ${{ secrets.SCALEWAY_SERVER_USER }}
      #   TF_VAR_scaleway_server_password: ${{ secrets.SCALEWAY_SERVER_PASSWORD }}
      #   TF_VAR_scaleway_ssh_key_id: ${{ secrets.SCALEWAY_SSH_KEY_ID }}
      #   TF_VAR_scaleway_zone: ${{ secrets.SCALEWAY_ZONE }}
      # run: |
      #   terraform plan -var="scaleway_access_key=${{ secrets.SCALEWAY_ACCESS_KEY }}" \
      #     -var="scaleway_secret_key=${{ secrets.SCALEWAY_SECRET_KEY }}" \
      #     -var="scaleway_project_id=${{ secrets.SCALEWAY_PROJECT_ID }}"
      # working-directory: ./terraform

    - name: Terraform Import
      continue-on-error: true
      uses: ./.github/actions/terraform
      with:
        command: import scaleway_baremetal_server.main ${{ secrets.SCALEWAY_ZONE }}/${{ secrets.SCALEWAY_SERVER_ID }}
      # env:
      #   SCW_ACCESS_KEY: ${{ secrets.SCALEWAY_ACCESS_KEY }}
      #   SCW_SECRET_KEY: ${{ secrets.SCALEWAY_SECRET_KEY }}
      #   SCW_DEFAULT_PROJECT_ID: ${{ secrets.SCALEWAY_PROJECT_ID }}
      #   TF_VAR_scaleway_access_key: ${{ secrets.SCALEWAY_ACCESS_KEY }}
      #   TF_VAR_scaleway_secret_key: ${{ secrets.SCALEWAY_SECRET_KEY }}
      #   TF_VAR_scaleway_organization_id: ${{ secrets.SCALEWAY_ORGANIZATION_ID }}
      #   TF_VAR_scaleway_project_id: ${{ secrets.SCALEWAY_PROJECT_ID }}
      #   TF_VAR_scaleway_server_name: ${{ secrets.SCALEWAY_SERVER_NAME }}
      #   TF_VAR_scaleway_server_id: ${{ secrets.SCALEWAY_SERVER_ID }}
      #   TF_VAR_scaleway_server_os_id: ${{ secrets.SCALEWAY_SERVER_OS_ID }}
      #   TF_VAR_scaleway_server_public_ip: ${{ secrets.SCALEWAY_SERVER_PUBLIC_IP }}
      #   TF_VAR_scaleway_server_user: ${{ secrets.SCALEWAY_SERVER_USER }}
      #   TF_VAR_scaleway_server_password: ${{ secrets.SCALEWAY_SERVER_PASSWORD }}
      #   TF_VAR_scaleway_ssh_key_id: ${{ secrets.SCALEWAY_SSH_KEY_ID }}
      #   TF_VAR_scaleway_zone: ${{ secrets.SCALEWAY_ZONE }}
      #   TF_LOG: DEBUG
      # #   TELEPORT_PROXY: ${{ secrets.TELEPORT_PROXY }}
      #   # TELEPORT_AUTH_SERVER: ${{ secrets.TELEPORT_AUTH_SERVER }}
      # # terraform import scaleway_baremetal_server.main ${{ secrets.SCALEWAY_SERVER_ID }}
      # run: |
      #   terraform import \
      #     -var="scaleway_access_key=${{ secrets.SCALEWAY_ACCESS_KEY }}" \
      #     -var="scaleway_secret_key=${{ secrets.SCALEWAY_SECRET_KEY }}" \
      #     -var="scaleway_project_id=${{ secrets.SCALEWAY_PROJECT_ID }}" \
      #     scaleway_baremetal_server.main ${{ secrets.SCALEWAY_ZONE }}/${{ secrets.SCALEWAY_SERVER_ID }}
      # continue-on-error: true
      # working-directory: ./terraform

    # - name: Terraform Plan
    #   run: terraform plan -no-color
    #   continue-on-error: true
    #   env:
    #     SCW_ACCESS_KEY: ${{ secrets.SCALEWAY_ACCESS_KEY }}
    #     SCW_SECRET_KEY: ${{ secrets.SCALEWAY_SECRET_KEY }}
    #     SCW_DEFAULT_PROJECT_ID: ${{ secrets.SCALEWAY_PROJECT_ID }}
    #     TF_VAR_scaleway_access_key: ${{ secrets.SCALEWAY_ACCESS_KEY }}
    #     TF_VAR_scaleway_secret_key: ${{ secrets.SCALEWAY_SECRET_KEY }}
    #     TF_VAR_scaleway_organization_id: ${{ secrets.SCALEWAY_ORGANIZATION_ID }}
    #     TF_VAR_scaleway_project_id: ${{ secrets.SCALEWAY_PROJECT_ID }}
    #     TF_VAR_scaleway_server_name: ${{ secrets.SCALEWAY_SERVER_NAME }}
    #     TF_VAR_scaleway_server_id: ${{ secrets.SCALEWAY_SERVER_ID }}
    #     TF_VAR_scaleway_server_os_id: ${{ secrets.SCALEWAY_SERVER_OS_ID }}
    #     TF_VAR_scaleway_server_public_ip: ${{ secrets.SCALEWAY_SERVER_PUBLIC_IP }}
    #     TF_VAR_scaleway_server_user: ${{ secrets.SCALEWAY_SERVER_USER }}
    #     TF_VAR_scaleway_server_password: ${{ secrets.SCALEWAY_SERVER_PASSWORD }}
    #     TF_VAR_scaleway_ssh_key_id: ${{ secrets.SCALEWAY_SSH_KEY_ID }}
    #     TF_VAR_scaleway_zone: ${{ secrets.SCALEWAY_ZONE }}
    #     TF_LOG: DEBUG
    #   working-directory: ./terraform

    - name: Apply Terraform configuration
      # if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      uses: ./.github/actions/terraform
      with:
        command: apply -auto-approve
      # env:
      #   SCW_ACCESS_KEY: ${{ secrets.SCALEWAY_ACCESS_KEY }}
      #   SCW_SECRET_KEY: ${{ secrets.SCALEWAY_SECRET_KEY }}
      #   SCW_DEFAULT_PROJECT_ID: ${{ secrets.SCALEWAY_PROJECT_ID }}
      #   TF_VAR_scaleway_access_key: ${{ secrets.SCALEWAY_ACCESS_KEY }}
      #   TF_VAR_scaleway_secret_key: ${{ secrets.SCALEWAY_SECRET_KEY }}
      #   TF_VAR_scaleway_organization_id: ${{ secrets.SCALEWAY_ORGANIZATION_ID }}
      #   TF_VAR_scaleway_project_id: ${{ secrets.SCALEWAY_PROJECT_ID }}
      #   TF_VAR_scaleway_server_name: ${{ secrets.SCALEWAY_SERVER_NAME }}
      #   TF_VAR_scaleway_server_id: ${{ secrets.SCALEWAY_SERVER_ID }}
      #   TF_VAR_scaleway_server_os_id: ${{ secrets.SCALEWAY_SERVER_OS_ID }}
      #   TF_VAR_scaleway_server_public_ip: ${{ secrets.SCALEWAY_SERVER_PUBLIC_IP }}
      #   TF_VAR_scaleway_server_user: ${{ secrets.SCALEWAY_SERVER_USER }}
      #   TF_VAR_scaleway_server_password: ${{ secrets.SCALEWAY_SERVER_PASSWORD }}
      #   TF_VAR_scaleway_ssh_key_id: ${{ secrets.SCALEWAY_SSH_KEY_ID }}
      #   TF_VAR_scaleway_zone: ${{ secrets.SCALEWAY_ZONE }}
      # run: terraform apply -auto-approve
      # working-directory: ./terraform
