name: CI Pipeline

on:
  push:
    branches:
      - main
    #   - 'features/**'
  pull_request:
    branches:
      - main

  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  RELEASE: 0.5.1    # /!\ increase this to avoid overwriting older image

jobs:

  build-and-push-image-api:

    name: API - build/push image
    # runs-on: ubuntu-latest
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.7

      - name: Run 'build-push' local action
        uses: ./.github/actions/build-push
        with:
          name: API
          src: api
          registry: ${{ env.REGISTRY }}
          actor: ${{ github.actor }}
          token: ${{ secrets.GITHUB_TOKEN }}
          image: pierrz/biggie_api_img
          tag: ${{ env.RELEASE }}
          labels: ${{ steps.meta.outputs.labels }}

  build-and-push-image-celery:

    name: Celery - build/push image
    # runs-on: ubuntu-latest
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.7

      - name: Run 'build-push' local action
        uses: ./.github/actions/build-push
        with:
          name: Celery
          src: celery_app
          registry: ${{ env.REGISTRY }}
          actor: ${{ github.actor }}
          token: ${{ secrets.GITHUB_TOKEN }}
          image: pierrz/biggie_celery_img
          tag: ${{ env.RELEASE }}
          labels: ${{ steps.meta.outputs.labels }}

  test:

    name: Tests
    needs: [build-and-push-image-api, build-and-push-image-celery]
    # runs-on: ubuntu-latest
    runs-on: self-hosted
    permissions:
      packages: write
      # specific to py-cov-action/python-coverage-comment-action (WIP)
      pull-requests: write
      contents: write

    env:
      CELERY_BROKER_URL: ${{ secrets.CELERY_BROKER_URL }}
      CELERY_RESULT_BACKEND: ${{ secrets.CELERY_RESULT_BACKEND }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_USER: ${{ secrets.DB_USER }}
      MONGODB_URI: ${{ secrets.MONGODB_URI }}
      MONGO_INITDB_ROOT_PASSWORD: ${{ secrets.MONGO_INITDB_ROOT_PASSWORD }}
      MONGO_INITDB_ROOT_USERNAME: ${{ secrets.MONGO_INITDB_ROOT_USERNAME }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      TOKEN_GITHUB_API: ${{ secrets.TOKEN_GITHUB_API }}
      DATA_DIR: ${{ secrets.DATA_DIR }}
      NETWORK: ci_network

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4.1.7

      - name: Log in to the Container registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create network & Mongo container
        run: |
          docker network create -d bridge ${{ env.NETWORK }}
          docker run -d --name ci_biggie_mongo \
            --env MONGO_INITDB_ROOT_USERNAME=${{ env.MONGO_INITDB_ROOT_USERNAME }} \
            --env MONGO_INITDB_ROOT_PASSWORD=${{ env.MONGO_INITDB_ROOT_PASSWORD }} \
            --network=${{ env.NETWORK }} \
            mongo:7.0.14

      # cd /home/runner/work/biggie/biggie/conf/postgres
      - name: Create Postgres container
        run: |
          docker build conf/postgres --tag biggie_postgres:latest
          docker run -d --name ci_biggie_postgres \
            --env POSTGRES_DB=${{ env.POSTGRES_DB }} \
            --env POSTGRES_USER=${{ env.POSTGRES_USER }} \
            --env POSTGRES_PASSWORD=${{ env.POSTGRES_PASSWORD }} \
            --env DB_NAME=${{ env.DB_NAME }} \
            --env DB_USER=${{ env.DB_USER }} \
            --env DB_PASSWORD=${{ env.DB_PASSWORD }} \
            --network=${{ env.NETWORK }} \
            biggie_postgres:latest

      - name: Create Spark containers (master and workers)
        run: |
          docker build conf/spark --tag biggie_spark:latest
          docker run -d --name ci_biggie_spark-master \
            --env SPARK_MODE=master \
            --publish 7077:7077 \
            --network=${{ env.NETWORK }} \
            biggie_spark:latest \
          && docker run -d --name ci_biggie_spark-worker-1 \
            --env SPARK_MODE=worker \
            --env SPARK_MASTER_URL=spark://spark-master:7077 \
            --network=${{ env.NETWORK }} \
            biggie_spark:latest \
          && docker run -d --name ci_biggie_spark-worker-2 \
            --env SPARK_MODE=worker \
            --env SPARK_MASTER_URL=spark://spark-master:7077 \
            --network=${{ env.NETWORK }} \
            biggie_spark:latest

      - name: Spark containers checks
        run: |
          docker network inspect ${{ env.NETWORK }} --format '{{range .Containers}}{{.Name}} {{end}}'
          # docker exec ci_biggie_spark-worker-1 nc -zv spark-master 7077
          # docker network inspect ${{ env.NETWORK }}
          # docker exec ci_biggie_spark-worker-1 ping -c 4 ci_biggie_spark-master
          # docker exec ci_biggie_spark-worker-2 ping -c 4 ci_biggie_spark-master
          # docker exec ci_biggie_spark-master ping -c 4 ci_biggie_spark-worker-1

      - name: Test API image
        run: |
          docker run --name ci_biggie_api-test \
            --env MONGODB_URI=${{ env.MONGODB_URI }} \
            --env DB_NAME=${{ env.DB_NAME }} \
            --env DB_USER=${{ env.DB_USER }} \
            --env DB_PASSWORD=${{ env.DB_PASSWORD }} \
            --network=${{ env.NETWORK }} \
            --volume ${{ github.workspace }}/${{ env.DATA_DIR }}:/opt/data \
            ghcr.io/pierrz/biggie_api_img:latest \
            sh -c "poetry install --only dev && \
            pytest -vv --cov-config=pyproject.toml --cov=. --cov-report=html && \
            mkdir /opt/data/api_coverage && cp .coverage /opt/data/api_coverage/.coverage"

      - name: Create Celery container
        run: |
          docker run --name ci_biggie_celery-test \
            --env CELERY_BROKER_URL=${{ env.CELERY_BROKER_URL }} \
            --env CELERY_RESULT_BACKEND=${{ env.CELERY_RESULT_BACKEND }} \
            --env MONGODB_URI=${{ env.MONGODB_URI }} \
            --env DB_NAME=${{ env.DB_NAME }} \
            --env DB_USER=${{ env.DB_USER }} \
            --env DB_PASSWORD=${{ env.DB_PASSWORD }} \
            --env TOKEN_GITHUB_API=${{ env.TOKEN_GITHUB_API }} \
            --env TEST_MODE="True" \
            --network=${{ env.NETWORK }} \
            --volume ${{ github.workspace }}/${{ env.DATA_DIR }}:/opt/data \
            ghcr.io/pierrz/biggie_celery_img:latest \
            sleep 10m
      
      - name: Test Celery image
        run: |
          docker exec -it ci_biggie_celery-test ping -c 4 ci_biggie_spark-master
          docker exec -it ci_biggie_celery-test ping -c 4 ci_biggie_spark-worker-1
          docker exec -it ci_biggie_celery-test \
          sh -c "poetry install --only dev && \
          python3.11 -m pytest -vv --asyncio-mode=strict --cov-config=pyproject.toml --cov=. --cov-report=html && \
          mkdir /opt/data/celery_coverage && cp .coverage /opt/data/celery_coverage/.coverage"

      - name: Upload merged coverage report
        uses: actions/upload-artifact@v4.4.0
        with:
          name: html-coverage-report
          path: |
            ${{ github.workspace }}/data/celery_coverage_html_report
            ${{ github.workspace }}/data/api_coverage_html_report

      # # Get names of all containers starting with biggie_
      # CONTAINER_NAMES=$(docker ps -a --format '{{.Names}}' | grep '^biggie_' || true)

      # if [ ! -z "$CONTAINER_NAMES" ]; then
      #   # Get volume names associated with the containers
      #   VOLUME_NAMES=$(docker container inspect $CONTAINER_NAMES \
      #     -f '{{range .Mounts}}{{if eq .Type "volume"}}{{.Name}} {{end}}{{end}}' | tr ' ' '\n' | sort -u | tr '\n' ' ') || echo "Failed to inspect containers"

      #   # Remove containers
      #   echo "Removing containers: $CONTAINER_NAMES"
      #   docker container rm -f $CONTAINER_NAMES || echo "Failed to remove some containers"

      #   # Remove volumes
      #   if [ ! -z "$VOLUME_NAMES" ]; then
      #     echo "Removing volumes: $VOLUME_NAMES"
      #     docker volume rm $VOLUME_NAMES || echo "Failed to remove some volumes"
      #   else
      #     echo "No volumes to remove"
      #   fi
      # else
      #   echo "No biggie_* containers found"
      # fi
      - name: Delete Docker elements in self-hosted runner
        if: always()
        run: |
          # Get volume names associated with the containers
          echo "Retrieving created volumes ..."
          VOLUME_NAMES=$(docker container inspect \
            ci_biggie_api-test ci_biggie_celery-test \
            ci_biggie_postgres ci_biggie_mongo \
            ci_biggie_spark-master ci_biggie_spark-worker-1 ci_biggie_spark-worker-2 \
            -f '{{range .Mounts}}{{if eq .Type "volume"}}{{.Name}} {{end}}{{end}}' | tr ' ' '\n' | sort -u | tr '\n' ' ') || true
          echo "$VOLUME_NAMES"

          # Remove containers
          echo "Removing created containers ..."
          docker container stop \
            ci_biggie_api-test ci_biggie_celery-test \
            ci_biggie_postgres ci_biggie_mongo \
            ci_biggie_spark-master ci_biggie_spark-worker-1 ci_biggie_spark-worker-2 || true
          docker container rm -f \
            ci_biggie_api-test ci_biggie_celery-test \
            ci_biggie_postgres ci_biggie_mongo \
            ci_biggie_spark-master ci_biggie_spark-worker-1 ci_biggie_spark-worker-2 || true

          # Remove volumes
          echo "Removing created volumes ..."
          if [ ! -z "$VOLUME_NAMES" ]; then
            docker volume rm $VOLUME_NAMES || true
          fi

          # Remove network
          echo "Removing created network ..."
          docker network rm ${{ env.NETWORK }} || true

      # TODO: fix py-cov-action/python-coverage-comment-action errors (permissions, absolute/relative files)
      # Cf. https://github.com/py-cov-action/python-coverage-comment-action?tab=readme-ov-file#merging-multiple-coverage-reports
      # Error: Cannot read .coverage files because files are absolute. You need to configure coverage to write relative paths by adding the following option to your coverage configuration file:
      # [run]
      # relative_files = true
      # Note that the specific format can be slightly different if you're using setup.cfg or pyproject.toml. See details in: https://coverage.readthedocs.io/en/latest/config.html#config-run-relative-files
      # Error: Critical error. This error possibly occurred because the permissions of the workflow are set incorrectly. You can see the correct setting of permissions here: https://github.com/py-cov-action/python-coverage-comment-action#basic-usage

      # for refined merging approach
      # - name: Merge coverage reports
      #   run: |
      #     ls -al ${{ github.workspace }}/data
      #     ls -al data
      #     pip install coverage
      #     coverage combine --keep ${{ github.workspace }}/data/.coverage.api ${{ github.workspace }}/data/.coverage.celery
      #     coverage html -d ${{ github.workspace }}/data
      #     cp ${{ github.workspace }}/data/.coverage ${{ github.workspace }}/data/merged_coverage/.coverage

      # - name: Comment coverage
      #   uses: py-cov-action/python-coverage-comment-action@v3.28
      #   with:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     COVERAGE_PATH: data/celery_coverage
      #     MINIMUM_GREEN: 80
      #     MINIMUM_ORANGE: 50
      #     COMMENT_TEMPLATE: |
      #       ### CELERY Coverage Report
      #       {coverage_report}

      # - name: Store Pull Request comment to be posted
      #   uses: actions/upload-artifact@v4
      #   if: steps.coverage_comment.outputs.COMMENT_FILE_WRITTEN == 'true'
      #   with:
      #     name: python-coverage-comment-action-celery
      #     path: python-coverage-comment-action.txt

      # - name: Comment coverage
      #   uses: py-cov-action/python-coverage-comment-action@v3.28
      #   with:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     COVERAGE_PATH: ${{ github.workspace }}/data/api_coverage
      #     MINIMUM_GREEN: 80
      #     MINIMUM_ORANGE: 50
      #     COMMENT_TEMPLATE: |
      #       ### API Coverage Report
      #       {coverage_report}

      # - name: Store Pull Request comment to be posted
      #   uses: actions/upload-artifact@v4
      #   if: steps.coverage_comment.outputs.COMMENT_FILE_WRITTEN == 'true'
      #   with:
      #     name: python-coverage-comment-action-api
      #     path: python-coverage-comment-action.txt
